insert into Customer (first_name, last_name, email, mobile, job) values ('Charlean', 'Fox', 'cfox0@mozilla.com', '1153520959', 'Budget/Accounting Analyst I');
insert into Customer (first_name, last_name, email, mobile, job) values ('Stefania', 'Menco', 'smenco1@zimbio.com', '3088231647', 'Dental Hygienist');
insert into Customer (first_name, last_name, email, mobile, job) values ('Ty', 'Normaville', 'tnormaville2@bandcamp.com', '3679964820', 'Dental Hygienist');
insert into Customer (first_name, last_name, email, mobile, job) values ('Lorette', 'Astling', 'lastling3@usnews.com', '5924974104', 'Software Consultant');
insert into Customer (first_name, last_name, email, mobile, job) values ('Honor', 'Abbado', 'habbado4@ucoz.com', '5306688309', 'Speech Pathologist');
insert into Customer (first_name, last_name, email, mobile, job) values ('Tiebold', 'Waltho', 'twaltho5@state.gov', '3906903876', 'Registered Nurse');
insert into Customer (first_name, last_name, email, mobile, job) values ('Camila', 'Sollas', 'csollas6@instagram.com', '9452743461', 'Software Test Engineer IV');
insert into Customer (first_name, last_name, email, mobile, job) values ('Maggie', 'Moran', 'mmoran7@ocn.ne.jp', '8281857516', 'Research Assistant I');
insert into Customer (first_name, last_name, email, mobile, job) values ('Tallie', 'Fergie', 'tfergie8@dedecms.com', '3283811106', 'Nuclear Power Engineer');
insert into Customer (first_name, last_name, email, mobile, job) values ('Dreddy', 'King', 'dking9@xinhuanet.com', '3753437150', 'Nurse Practicioner');
insert into Customer (first_name, last_name, email, mobile, job) values ('Teddy', 'Bubb', 'tbubba@soup.io', '8489528253', 'Sales Representative');
insert into Customer (first_name, last_name, email, mobile, job) values ('Orelee', 'Gross', 'ogrossb@skyrock.com', '9874105471', 'VP Sales');
insert into Customer (first_name, last_name, email, mobile, job) values ('Nerita', 'Triner', 'ntrinerc@webnode.com', '4627807243', 'Help Desk Operator');
insert into Customer (first_name, last_name, email, mobile, job) values ('Nalani', 'Keniwell', 'nkeniwelld@live.com', '3211744135', 'Community Outreach Specialist');
insert into Customer (first_name, last_name, email, mobile, job) values ('Corie', 'Di Biaggi', 'cdibiaggie@i2i.jp', '7288769787', 'Biostatistician I');
insert into Customer (first_name, last_name, email, mobile, job) values ('Quintin', 'Molson', 'qmolsonf@posterous.com', '4688376096', 'VP Product Management');
insert into Customer (first_name, last_name, email, mobile, job) values ('Ivan', 'Puvia', 'ipuviag@ustream.tv', '4358855416', 'VP Product Management');
insert into Customer (first_name, last_name, email, mobile, job) values ('Hyacinthe', 'Goldson', 'hgoldsonh@networkadvertising.org', '8062223451', 'Technical Writer');
insert into Customer (first_name, last_name, email, mobile, job) values ('Marline', 'Shilston', 'mshilstoni@ovh.net', '7468558721', 'Director of Sales');
insert into Customer (first_name, last_name, email, mobile, job) values ('Wendell', 'Mott', 'wmottj@indiegogo.com', '9713852977', 'Mechanical Systems Engineer');
