insert into Customer (id, first_name, last_name, email, mobile, job) values (1, 'Margy', 'Rosenstiel', 'mrosenstiel0@google.co.uk', '2054185640', 'Pharmacist');
insert into Customer (id, first_name, last_name, email, mobile, job) values (2, 'Roger', 'Cominoli', 'rcominoli1@huffingtonpost.com', '9646517911', 'Dental Hygienist');
insert into Customer (id, first_name, last_name, email, mobile, job) values (3, 'Nye', 'Dominey', 'ndominey2@bloglines.com', '1538633400', 'Senior Sales Associate');
insert into Customer (id, first_name, last_name, email, mobile, job) values (4, 'Dominga', 'Jaycock', 'djaycock3@omniture.com', '4323997185', 'Payment Adjustment Coordinator');
insert into Customer (id, first_name, last_name, email, mobile, job) values (5, 'Yvonne', 'Olivello', 'yolivello4@ifeng.com', '6075499327', 'Systems Administrator I');
insert into Customer (id, first_name, last_name, email, mobile, job) values (6, 'Sisely', 'Dresser', 'sdresser5@psu.edu', '2858072829', 'Sales Associate');
insert into Customer (id, first_name, last_name, email, mobile, job) values (7, 'Hobey', 'Render', 'hrender6@webs.com', '5905557217', 'Senior Cost Accountant');
insert into Customer (id, first_name, last_name, email, mobile, job) values (8, 'Ketti', 'Boase', 'kboase7@vinaora.com', '9205365608', 'Nurse');
insert into Customer (id, first_name, last_name, email, mobile, job) values (9, 'Sib', 'Panter', 'spanter8@wikispaces.com', '9755453756', 'Analyst Programmer');
insert into Customer (id, first_name, last_name, email, mobile, job) values (10, 'Amalea', 'Ropartz', 'aropartz9@ycombinator.com', '2875902132', 'Payment Adjustment Coordinator');
insert into Customer (id, first_name, last_name, email, mobile, job) values (11, 'Craggie', 'Van Rembrandt', 'cvanrembrandta@wp.com', '2431946109', 'Sales Associate');
insert into Customer (id, first_name, last_name, email, mobile, job) values (12, 'Barton', 'Knightly', 'bknightlyb@princeton.edu', '8208167827', 'Executive Secretary');
insert into Customer (id, first_name, last_name, email, mobile, job) values (13, 'Wash', 'Dullard', 'wdullardc@ameblo.jp', '6261689431', 'Sales Associate');
insert into Customer (id, first_name, last_name, email, mobile, job) values (14, 'Kandace', 'Streeter', 'kstreeterd@instagram.com', '1757201965', 'Software Consultant');
insert into Customer (id, first_name, last_name, email, mobile, job) values (15, 'Nevsa', 'Geistmann', 'ngeistmanne@nasa.gov', '7125483463', 'Safety Technician III');
insert into Customer (id, first_name, last_name, email, mobile, job) values (16, 'Cassandry', 'Walton', 'cwaltonf@who.int', '8273355971', 'Internal Auditor');
insert into Customer (id, first_name, last_name, email, mobile, job) values (17, 'Odille', 'Seville', 'osevilleg@mozilla.org', '5831190288', 'Nurse');
insert into Customer (id, first_name, last_name, email, mobile, job) values (18, 'June', 'Nudde', 'jnuddeh@paypal.com', '1125671141', 'Food Chemist');
insert into Customer (id, first_name, last_name, email, mobile, job) values (19, 'Violet', 'Gainsford', 'vgainsfordi@homestead.com', '1778433067', 'Software Engineer III');
insert into Customer (id, first_name, last_name, email, mobile, job) values (20, 'Val', 'Spier', 'vspierj@taobao.com', '4627033725', 'Design Engineer');
